name: fluttersteem
description: Unofficial Steem client library for Dart and Flutter
version: 0.0.2
author: steem/@amigos <mkaa22@gmail.com>
homepage: https://github.com/mortea15/fluttersteem

environment:
  sdk: ">=1.22.0 <2.0.0"

dependencies:
  oauth2: ^1.0.0
  owl: ^0.2.1

dev_dependencies:
  build_runner: ^0.3.0
  owl_codegen: ^0.2.1
  test: ^0.12.0